### ISSUE TITLE
Convert Static Data Files to `json` and `csv`

### ISSUE THREAD

**Issue by michaelweinold** [michaelweinold/bw_hybrid#31]
Currently, data files are of formats `txt`, `csv`, `xlsx`. To avoid using unsafe functions like `eval()` and to simpify data import, all data should be converted to either `json` or `csv`.

File names should indicate the target Python type (e.g.: `dict_ecoinvent_aux_data.json` or `list_geography_correspondence.json`.

## Task List
 - [ ] `countries_per_regions.txt`
 - [ ] `countries.txt`
 - [ ] `Filter.xlsx`
 - [ ] `geography_replacements.txt`
 - [ ] `Product_Concordances.xlsx`
 - [ ] `STAM_categories.txt`
 - [ ] `STAM_functional_categories.txt`

**Comment by michaelweinold** [comment]
Relevant notebooks:

[`json_export.ipynb`](https://github.com/michaelweinold/bw_hybrid/blob/master/dev/4_function_refactoring/2_data_preparation/2_1_json_export.ipynb)

**Comment by michaelweinold** [comment]
Compare also follow-up issue: https://github.com/michaelweinold/bw_hybrid/issues/32
